---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-home-pv
  annotations:
    pv.kubernetes.io/provisioned-by: filestore.csi.storage.gke.io
spec:
  storageClassName: csi-filestore
  capacity:
    storage: 2.5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    # Modify this to use the zone, filestore instance and share name.
    volumeHandle: "modeInstance/us-central1-b/csi-home/csi_home"
    volumeAttributes:
      ip: 10.161.1.2
      volume: csi_home
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-project-pv
  annotations:
    pv.kubernetes.io/provisioned-by: filestore.csi.storage.gke.io
spec:
  storageClassName: csi-filestore
  capacity:
    storage: 2.5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    # Modify this to use the zone, filestore instance and share name.
    volumeHandle: "modeInstance/us-central1-b/csi-project/csi_project"
    volumeAttributes:
      ip: 10.161.1.10
      volume: csi_project
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-scratch-pv
  annotations:
    pv.kubernetes.io/provisioned-by: filestore.csi.storage.gke.io
spec:
  storageClassName: csi-filestore
  capacity:
    storage: 2.5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    # Modify this to use the zone, filestore instance and share name.
    volumeHandle: "modeInstance/us-central1-b/csi-scratch/csi_scratch"
    volumeAttributes:
      ip: 10.161.1.18
      volume: csi_scratch

