---
apiVersion: v1
kind: Pod
metadata:
  name: csi-concurrent-pod3
  namespace: csi-test
spec:
  containers:
  - name: main
    image: ubuntu:latest
    args: [ "tail", "-f", "/dev/null" ]
    volumeMounts:
    - mountPath: /csi/scratch
      name: concurrent-scratch
  volumes:
  - name: concurrent-scratch
    persistentVolumeClaim:
      claimName: csi-concurrent-scratch-pvc3
